[package]
name = "alacritty-wal"
version = "0.2.0"
authors = ["abyss <derribado@tutanota.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
dirs-next = "1.0.1"
enum-map = "0.6.2"
anyhow = "1.0.31"
structopt = "0.3.15"
